import type { ProductTreatmentState } from "../schemas/productState";

export const initialState: ProductTreatmentState = {
  metadata: {
    projectName: "Untitled Product Page",
    currentStep: "productPromise",
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  brand: {
    brand: "",
    brandLogo: "",
  },
  product: {
    productName: "",
    category: "",
    shortDescription: "",
    productPromise: "",
    primaryUse: "",
    customerHypothesis: "",
    mainFeatures: "",
  },
  identity: {
    productId: "",
    sku: "",
    gtin: "UNKNOWN",
    subcategory: "",
    variant: "",
    edition: "",
    model: "",
    originCountry: "",
    originRegion: "",
    format: "",
    capacity: "",
    abv: "",
    batchLotLogic: "",
    technicalSpecs: "",
    status: "UNKNOWN",
  },
  navigation: {
    store: "",
    breadcrumb: "",
    slug: "",
    canonicalUrl: "",
    navigationLabels: "",
  },
  media: [
    { id: "photo-1", role: "HERO_RECOGNITION", altText: "", approvalStatus: "UNKNOWN", usageRights: "", isMain: true, crop: { zoom: 1, x: 0, y: 0 } },
    { id: "photo-2", role: "DETAIL_QUALITY", altText: "", approvalStatus: "UNKNOWN", usageRights: "", isMain: false, crop: { zoom: 1, x: 0, y: 0 } },
    { id: "photo-3", role: "RITUAL_USE_DESIRE", altText: "", approvalStatus: "UNKNOWN", usageRights: "", isMain: false, crop: { zoom: 1, x: 0, y: 0 } },
    { id: "photo-4", role: "PACKAGING_TRUST", altText: "", approvalStatus: "UNKNOWN", usageRights: "", isMain: false, crop: { zoom: 1, x: 0, y: 0 } },
  ],
  benefits: [{ id: "benefit-1", feature: "", benefit: "", evidence: "" }],
  trust: [{ id: "claim-1", claim: "", owner: "", source: "", status: "UNKNOWN", approval: "", market: "" }],
  pricing: {
    currency: "EUR",
    grossPrice: 0,
    taxRate: 21,
    taxIncluded: true,
    referencePrice: 0,
    discountType: "NONE",
    discountValue: 0,
  },
  inventory: {
    stockStatus: "AVAILABLE",
    stockQty: 0,
    lowStockThreshold: 5,
    availabilityMessage: "",
    quantity: 1,
  },
  ctas: {
    primary: { enabled: true, label: "Buy now", action: "checkout", destination: "" },
    secondary: { enabled: true, label: "Ask for advice", action: "contact", destination: "" },
    personalisation: { enabled: false, label: "Personalize", action: "personalisation", destination: "" },
  },
  commercialTerms: {
    paymentMethods: "",
    shipping: "",
    deliveryWindow: "",
    returns: "",
    refund: "",
    warranty: "",
    legalAge: "",
    securePayment: true,
  },
  service: {
    dispatchSla: "",
    deliverySla: "",
    carrier: "",
    breakagePolicy: "",
    customerService: "",
  },
  relationship: {
    customerArea: false,
    registration: "",
    consent: "",
    npsTrigger: "",
    crmDestination: "",
  },
  seoAio: {
    seoTitle: "",
    metaDescription: "",
    keywords: "",
    semanticEntities: "",
    faq: "",
    language: "Spanish",
    aiConditions: "Unknown fields must remain explicitly UNKNOWN. Do not invent claims, certifications, reviews, stock or availability.",
  },
  crossSell: [{ id: "cross-1", title: "", type: "", price: "", cta: "" }],
  theme: {
    primaryColor: "#0B1F3A",
    secondaryColor: "#1D7FE8",
    backgroundColor: "#FFFFFF",
    ctaColor: "#101820",
    fontOption: "Inter",
  },
  status: {
    publishStatus: "DRAFT",
  },
};
