import type { ImageCrop, MediaAsset, ProductTreatmentState } from "../schemas/productState";

const defaultCrop: ImageCrop = {
  zoom: 1,
  x: 50,
  y: 50,
  cropX: 0,
  cropY: 0,
  cropWidth: 100,
  cropHeight: 100,
};

export const emptyMedia: MediaAsset[] = [
  { id: "photo-1", role: "HERO_RECOGNITION", title: "Hero / Recognition", altText: "PENDING", approvalStatus: "PENDING", usageRights: "PENDING", isMain: true, order: 1, sourceType: "empty", crop: defaultCrop },
  { id: "photo-2", role: "DETAIL_QUALITY", title: "Detail / Quality", altText: "PENDING", approvalStatus: "PENDING", usageRights: "PENDING", isMain: false, order: 2, sourceType: "empty", crop: defaultCrop },
  { id: "photo-3", role: "RITUAL_USE_DESIRE", title: "Ritual / Use / Desire", altText: "PENDING", approvalStatus: "PENDING", usageRights: "PENDING", isMain: false, order: 3, sourceType: "empty", crop: defaultCrop },
  { id: "photo-4", role: "PACKAGING_TRUST", title: "Packaging / Trust", altText: "PENDING", approvalStatus: "PENDING", usageRights: "PENDING", isMain: false, order: 4, sourceType: "empty", crop: defaultCrop },
];

export const initialState: ProductTreatmentState = {
  metadata: {
    projectName: "Untitled Product Page",
    currentStep: "productPromise",
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  brand: {
    brand: "",
    assets: {
      brandLogo: "PENDING",
      labelLogo: "PENDING",
      profileLogo: "PENDING",
    },
  },
  product: {
    productName: "",
    category: "",
    subcategory: "",
    shortDescription: "",
    productPromise: "",
    primaryUse: "",
    mainFeatures: "",
    useCases: "",
    customerHypothesis: "",
  },
  identity: {
    productId: "PENDING",
    sku: "",
    gtin: "PENDING",
    variant: "",
    edition: "",
    model: "PENDING",
    originCountry: "",
    originRegion: "",
    composition: "",
    format: "",
    capacity: "",
    technicalSpecs: "PENDING",
    abv: "",
    lotBatchLogic: "PENDING",
    status: "PENDING",
  },
  catalogue: {
    store: "PENDING",
    breadcrumb: "",
    slug: "",
    canonicalUrl: "PENDING",
    labels: "",
  },
  media: emptyMedia,
  benefits: [{ id: "benefit-1", feature: "", benefit: "", evidence: "PENDING" }],
  trust: [{ id: "claim-1", claim: "", owner: "PENDING", source: "PENDING", status: "PENDING", reviewDate: "PENDING", approvalStatus: "PENDING", market: "PENDING" }],
  evidence: {
    trustBadges: "PENDING",
    originEvidence: "PENDING",
    lotEvidence: "PENDING",
    certificate: "PENDING",
    laboratoryEvidence: "PENDING",
    guarantee: "PENDING",
    supplierEvidence: "PENDING",
    responsibleUse: "PENDING",
  },
  pricing: {
    currency: "EUR",
    grossPrice: 0,
    taxRate: 21,
    taxIncluded: true,
    referencePrice: 0,
    discountType: "NONE",
    discountValue: 0,
    quantityTiers: "PENDING",
    promoCode: "PENDING",
    validFrom: "PENDING",
    validTo: "PENDING",
  },
  inventory: {
    stockStatus: "AVAILABLE",
    stockQty: 0,
    lowStockThreshold: 5,
    availabilityMessage: "PENDING",
    nextLot: "PENDING",
    quantity: 1,
  },
  variants: [{ id: "variant-1", variant: "PENDING", option: "PENDING", pack: "PENDING", quantity: "1", personalisation: "PENDING" }],
  ctas: {
    primary: { enabled: true, label: "Buy now", action: "checkout", destination: "PENDING" },
    secondary: { enabled: true, label: "Ask for advice", action: "contact", destination: "PENDING" },
    personalisation: { enabled: false, label: "Personalize", action: "personalisation", destination: "PENDING" },
    save: true,
    share: true,
    help: true,
    chat: true,
  },
  commercialTerms: {
    paymentMethods: "PENDING",
    securePayment: true,
    shipping: "PENDING",
    deliveryWindow: "PENDING",
    marketRestrictions: "PENDING",
    orderConditions: "PENDING",
    legalAge: "PENDING",
    returns: "PENDING",
    refund: "PENDING",
    warranty: "PENDING",
  },
  service: {
    dispatchSla: "PENDING",
    deliverySla: "PENDING",
    carrier: "PENDING",
    breakagePolicy: "PENDING",
    incidentRoute: "PENDING",
    rma: "PENDING",
    returnsRoute: "PENDING",
    refundRoute: "PENDING",
    customerService: "PENDING",
    postSaleCommunication: "PENDING",
    stockIncidentHandling: "PENDING",
  },
  relationship: {
    customerArea: false,
    registration: "PENDING",
    consent: "PENDING",
    npsTrigger: "PENDING",
    referral: "PENDING",
    loyalty: "PENDING",
    reactivation: "PENDING",
    crmDestination: "PENDING",
  },
  seoAio: {
    seoTitle: "",
    metaDescription: "",
    keywords: "",
    semanticEntities: "",
    faq: "PENDING",
    approvedClaims: "PENDING",
    productSchema: "PENDING",
    offerSchema: "PENDING",
    market: "PENDING",
    language: "Spanish",
    aiReadableConditions: "Unknown fields must remain explicitly UNKNOWN or PENDING. Do not invent facts, claims, evidence, certifications, reviews, stock or availability.",
  },
  crossSell: [{ id: "cross-1", type: "PENDING", title: "PENDING", price: "PENDING", cta: "PENDING" }],
  theme: {
    primaryColor: "#003B5C",
    secondaryColor: "#0A6FAE",
    backgroundColor: "#FFFFFF",
    ctaColor: "#05070B",
    fontOption: "Inter",
  },
  status: {
    publishStatus: "DRAFT",
  },
};