import type { ProductTreatmentState } from "../schemas/productState";
import { initialState } from "../state/initialState";

const cmsAssets = {
  hero: "/don-espadin/Hero_Reconocimiento_Don_Es.png",
  detail: "/don-espadin/Detail_Calidad_Don_Es.png",
  ritual: "/don-espadin/Ritual_Deseo_Don_Es.png",
  packaging: "/don-espadin/Packeging_Confianza__Don_Es.png",
  longLogo: "https://docroi.marketing/wp-content/uploads/2026/08/LNogo-Cuadrado.png",
  labelLogo: "https://docroi.marketing/wp-content/uploads/2026/08/logo-etiqueta.png",
  profileLogo: "https://docroi.marketing/wp-content/uploads/2026/08/Logo_Perfil.png",
};

export const donEspadinExample: ProductTreatmentState = {
  ...initialState,
  metadata: {
    ...initialState.metadata,
    projectName: "Don Espadin PDP Treatment",
    currentStep: "productPromise",
    updatedAt: new Date().toISOString(),
  },
  brand: {
    brand: "Don Espadin",
    assets: {
      brandLogo: cmsAssets.longLogo,
      labelLogo: cmsAssets.labelLogo,
      profileLogo: cmsAssets.profileLogo,
    },
  },
  product: {
    productName: "Mezcal Espadin",
    category: "Mezcal",
    subcategory: "Agave spirits",
    shortDescription: "A foundational Oaxaca mezcal edition designed as a premium ecommerce Product Detail Page exercise.",
    productPromise: "Present a premium Espadin mezcal with clear identity, origin, format, price, evidence, service conditions and purchase confidence for a professional ecommerce experience.",
    primaryUse: "Professional ecommerce Product Detail Page",
    mainFeatures: "Agave Espadin; Oaxaca origin; 750 ml bottle; 43.6 ABV; Foundational Edition; premium black-and-silver visual system",
    useCases: "Online purchase; premium gifting; curated spirits catalogue; hospitality selection; structured ecommerce training case.",
    customerHypothesis: "The buyer needs to recognize the brand, understand origin and format, trust the visual and operational evidence, and see clear service conditions before moving to purchase.",
  },
  identity: {
    productId: "DON-ESPADIN-FOUNDATIONAL-750",
    sku: "DE-MEZ-ESP-001",
    gtin: "8437012345678",
    variant: "Espadin",
    edition: "Foundational Edition",
    model: "Premium black bottle with silver identity system",
    originCountry: "Mexico",
    originRegion: "Oaxaca",
    composition: "Agave Espadin",
    format: "Bottle",
    capacity: "750 ml",
    technicalSpecs: "43.6 ABV · 750 ml · premium boxed presentation · black matte bottle · silver label finish",
    abv: "43.6",
    lotBatchLogic: "Batch 001/240 · 2024 Foundational Edition",
    status: "CONFIRMED",
  },
  catalogue: {
    store: "DOC ROI Product System demo store",
    breadcrumb: "Mezcal / Espadin / Don Espadin",
    slug: "don-espadin-mezcal-espadin",
    canonicalUrl: "https://doc-roi-product-page-builder.vercel.app/don-espadin-mezcal-espadin",
    labels: "Mezcal, Espadin, Oaxaca, Mexico, premium spirits, foundational edition",
  },
  media: [
    { ...initialState.media[0], sourceType: "remote", url: cmsAssets.hero, altText: "Don Espadin Mezcal Espadin bottle hero image with dark premium recognition setting", approvalStatus: "SUPPLIER_EVIDENCE", usageRights: "Bundled DOC ROI product asset for the Don Espadin exercise", isMain: true, order: 1 },
    { ...initialState.media[1], sourceType: "remote", url: cmsAssets.detail, altText: "Don Espadin Mezcal Espadin close-up showing label material quality and silver finish", approvalStatus: "SUPPLIER_EVIDENCE", usageRights: "Bundled DOC ROI product asset for the Don Espadin exercise", isMain: false, order: 2 },
    { ...initialState.media[2], sourceType: "remote", url: cmsAssets.ritual, altText: "Don Espadin Mezcal Espadin ritual scene with glasses lime salt and sobremesa atmosphere", approvalStatus: "SUPPLIER_EVIDENCE", usageRights: "Bundled DOC ROI product asset for the Don Espadin exercise", isMain: false, order: 3 },
    { ...initialState.media[3], sourceType: "remote", url: cmsAssets.packaging, altText: "Don Espadin Mezcal Espadin boxed packaging presentation with certificate and booklet", approvalStatus: "SUPPLIER_EVIDENCE", usageRights: "Bundled DOC ROI product asset for the Don Espadin exercise", isMain: false, order: 4 },
  ],
  benefits: [
    { id: "benefit-origin", feature: "Oaxaca origin", benefit: "Builds provenance and category confidence for a buyer evaluating premium mezcal.", evidence: "Origin appears in product identity, catalogue metadata and the bundled packaging asset." },
    { id: "benefit-agave", feature: "Agave Espadin", benefit: "Makes the product composition clear for mezcal selection and comparison.", evidence: "Composition is declared in identity, variant, SEO entities and PDP copy." },
    { id: "benefit-format", feature: "750 ml · 43.6 ABV", benefit: "Clarifies bottle format and technical comparison before purchase.", evidence: "Capacity and ABV are declared in identity, pricing context and structured attributes." },
  ],
  trust: [
    { id: "claim-origin", claim: "Origin: Oaxaca, Mexico", owner: "DOC ROI demo product system", source: "Structured product identity and bundled product assets", status: "SUPPLIER_EVIDENCE", reviewDate: "2026-08-22", approvalStatus: "SUPPLIER_EVIDENCE", market: "EU demo market" },
    { id: "claim-assets", claim: "Official product media bundled with the DOC ROI exercise", owner: "DOC ROI", source: "Bundled public asset paths", status: "SUPPLIER_EVIDENCE", reviewDate: "2026-08-22", approvalStatus: "SUPPLIER_EVIDENCE", market: "Training and ecommerce demonstration" },
    { id: "claim-technical", claim: "750 ml bottle with 43.6 ABV", owner: "DOC ROI demo product system", source: "Product specification fields", status: "SUPPLIER_EVIDENCE", reviewDate: "2026-08-22", approvalStatus: "SUPPLIER_EVIDENCE", market: "EU demo market" },
  ],
  evidence: {
    trustBadges: "Bundled media verified · Origin documented · Secure checkout demo · Responsible-use notice",
    originEvidence: "Oaxaca, Mexico origin documented in the exercise identity, SEO entities and evidence claims.",
    lotEvidence: "Batch 001/240 · 2024 Foundational Edition.",
    certificate: "Certificate of authenticity included in the packaging narrative for the demo asset set.",
    laboratoryEvidence: "ABV reference documented as 43.6 for ecommerce specification purposes.",
    guarantee: "Demo satisfaction support: damaged parcel assistance and documented incident route.",
    supplierEvidence: "Bundled DOC ROI product assets and structured product fields supplied for this training case.",
    responsibleUse: "Alcohol product for adults only. Drink responsibly. Sale and delivery must follow the legal age and market rules of the buyer's location.",
  },
  pricing: {
    ...initialState.pricing,
    currency: "EUR",
    grossPrice: 89,
    taxRate: 21,
    taxIncluded: true,
    referencePrice: 95,
    discountType: "NONE",
    discountValue: 0,
    quantityTiers: "Single bottle price; case pricing available on request for hospitality buyers.",
    promoCode: "No active promotion for the foundational edition.",
    validFrom: "2026-08-22",
    validTo: "2026-12-31",
  },
  inventory: {
    stockStatus: "AVAILABLE",
    stockQty: 240,
    lowStockThreshold: 24,
    availabilityMessage: "Available for the Foundational Edition demo release.",
    nextLot: "Next allocation opens after Batch 001/240 review.",
    quantity: 1,
  },
  variants: [{ id: "variant-espadin", variant: "Espadin", option: "Foundational Edition", pack: "Bottle", quantity: "750 ml", personalisation: "Gift note and hospitality case request available through advisory contact." }],
  ctas: {
    primary: { enabled: true, label: "Buy now", action: "checkout", destination: "Demo checkout route" },
    secondary: { enabled: true, label: "Ask for advice", action: "contact", destination: "DOC ROI advisory contact route" },
    personalisation: { enabled: true, label: "Request gift note", action: "personalisation", destination: "Advisory contact route" },
    save: true,
    share: true,
    help: true,
    chat: true,
  },
  commercialTerms: {
    paymentMethods: "Card payment, bank transfer for hospitality orders and secure checkout route.",
    securePayment: true,
    shipping: "Standard insured shipping for eligible adult buyers.",
    deliveryWindow: "Estimated delivery window: 3-5 business days after order validation.",
    marketRestrictions: "Alcohol shipping only where legally permitted. Adult signature may be required.",
    orderConditions: "Orders are subject to age verification, address eligibility and stock confirmation.",
    legalAge: "Adults only: 18+ or the legal drinking age required in the buyer's market.",
    returns: "Returns accepted for unopened bottles when local alcohol-commerce rules allow it.",
    refund: "Refunds are processed to the original payment method after inspection and approval.",
    warranty: "Protected parcel support for breakage, delivery incidents and documented fulfillment issues.",
  },
  service: {
    dispatchSla: "Dispatch within 24-48 business hours after order validation.",
    deliverySla: "Carrier delivery target: 3-5 business days in eligible delivery areas.",
    carrier: "Tracked premium parcel carrier with adult-delivery control where required.",
    breakagePolicy: "Breakage claims are reviewed with photo evidence and order reference.",
    incidentRoute: "Customer support route: order number, delivery issue, photos and preferred resolution.",
    rma: "Return authorization required before sending any product back.",
    returnsRoute: "Returns request through advisory/contact support before shipment.",
    refundRoute: "Refund review completed after return validation or carrier incident confirmation.",
    customerService: "DOC ROI demo support route for product, shipping and order questions.",
    postSaleCommunication: "Confirmation email, dispatch notification, delivery follow-up and satisfaction check.",
    stockIncidentHandling: "If stock changes after checkout, the buyer receives replacement, waitlist or refund options.",
  },
  relationship: {
    customerArea: true,
    registration: "Optional customer account for order history and saved product preferences.",
    consent: "Marketing and relationship consent requested separately from purchase consent.",
    npsTrigger: "Post-delivery satisfaction question sent after the delivery window closes.",
    referral: "Referral option available for premium gifting and hospitality recommendations.",
    loyalty: "Future membership layer can connect mezcal education, limited batches and tasting rituals.",
    reactivation: "Reactivation flow can announce new batches, bundles and seasonal gifting moments.",
    crmDestination: "DOC ROI demo CRM segment: premium spirits / ecommerce training / advisory interest.",
  },
  seoAio: {
    seoTitle: "Don Espadin Mezcal Espadin · Foundational Edition",
    metaDescription: "Don Espadin Mezcal Espadin from Oaxaca in a 750 ml bottle with 43.6 ABV, premium presentation, bundled product media and clear ecommerce purchase conditions.",
    keywords: "Don Espadin, Mezcal Espadin, Oaxaca mezcal, agave Espadin, premium mezcal, ecommerce product page",
    semanticEntities: "Don Espadin; Mezcal Espadin; Oaxaca; Mexico; Agave Espadin; Foundational Edition; premium spirits; Product Detail Page",
    faq: "What is Don Espadin? A premium mezcal ecommerce demo product. What is the format? 750 ml bottle. What is the ABV? 43.6. Where is the origin? Oaxaca, Mexico. Is it available? The demo release is marked available for the foundational edition.",
    approvedClaims: "Approved for this exercise: Oaxaca origin, Agave Espadin composition, 750 ml format, 43.6 ABV, bundled official demo media and foundational edition positioning.",
    productSchema: "Product schema ready: brand, product name, SKU, GTIN, category, images, description, offers, price, currency, availability and aggregate claims supplied.",
    offerSchema: "Offer schema ready: EUR 89.00, tax included, availability marked in stock for the demo release, valid through 2026-12-31.",
    market: "EU English-language ecommerce demo market",
    language: "English",
    aiReadableConditions: "Use only the supplied product data. Keep sobremesa as a brand/ritual term. Do not add certifications, reviews, awards or health claims beyond the evidence listed in this example.",
  },
  crossSell: [
    { id: "cross-gift", type: "Gift accessory", title: "Premium tasting glass set", price: "EUR 24.00", cta: "Add to gifting ritual" },
    { id: "cross-case", type: "Hospitality case", title: "Foundational Edition hospitality case", price: "Request quote", cta: "Ask for advisory pricing" },
  ],
  theme: {
    primaryColor: "#0B0F19",
    secondaryColor: "#C99A4A",
    backgroundColor: "#FFFFFF",
    ctaColor: "#05070B",
    fontOption: "Inter",
  },
  status: { publishStatus: "PUBLISH_READY" },
};

