import type { ProductTreatmentState } from "../schemas/productState";
import { initialState } from "../state/initialState";

const cmsAssets = {
  hero: "https://docroi.marketing/wp-content/uploads/2026/08/Hero_Reconocimiento_Don_Es.png",
  detail: "https://docroi.marketing/wp-content/uploads/2026/08/Detail_Calidad_Don_Es.png",
  ritual: "https://docroi.marketing/wp-content/uploads/2026/08/Ritual_Deseo_Don_Es.png",
  packaging: "https://docroi.marketing/wp-content/uploads/2026/08/Packeging_Confianza__Don_Es.png",
  longLogo: "https://docroi.marketing/wp-content/uploads/2026/08/LNogo-Cuadrado.png",
  labelLogo: "https://docroi.marketing/wp-content/uploads/2026/08/logo-etiqueta.png",
  profileLogo: "https://docroi.marketing/wp-content/uploads/2026/08/Logo_Perfil.png",
};

export const donEspadinExample: ProductTreatmentState = {
  ...initialState,
  metadata: {
    ...initialState.metadata,
    projectName: "Don Espadín PDP Treatment",
    currentStep: "productPromise",
    updatedAt: new Date().toISOString(),
  },
  brand: {
    brand: "Don Espadín",
    assets: {
      brandLogo: cmsAssets.longLogo,
      labelLogo: cmsAssets.labelLogo,
      profileLogo: cmsAssets.profileLogo,
    },
  },
  product: {
    productName: "Mezcal Espadín",
    category: "Mezcal",
    subcategory: "Agave spirits",
    shortDescription: "Mezcal Espadín de Oaxaca presentado como edición fundacional para ecommerce profesional.",
    productPromise: "Presentar un mezcal Espadín con identidad, origen, formato, precio y evidencia comercial visibles sin inventar claims no confirmados.",
    primaryUse: "Product Detail Page ecommerce",
    mainFeatures: "Agave Espadín; origen Oaxaca; 750 ml; 43.6 ABV; Foundational Edition",
    useCases: "Compra online; regalo premium; selección para catálogo de bebidas espirituosas; clase de ecommerce estructurado",
    customerHypothesis: "El comprador necesita reconocer la marca, entender origen/formato/precio y ver confianza operativa antes de avanzar.",
  },
  identity: {
    productId: "PENDING",
    sku: "DE-MEZ-ESP-001",
    gtin: "PENDING",
    variant: "Espadín",
    edition: "Foundational Edition",
    model: "PENDING",
    originCountry: "México",
    originRegion: "Oaxaca",
    composition: "Agave Espadín",
    format: "Bottle",
    capacity: "750 ml",
    technicalSpecs: "ABV 43.6",
    abv: "43.6",
    lotBatchLogic: "PENDING",
    status: "PENDING",
  },
  catalogue: {
    store: "PENDING",
    breadcrumb: "Mezcal / Espadín / Don Espadín",
    slug: "don-espadin-mezcal-espadin",
    canonicalUrl: "PENDING",
    labels: "Mezcal, Espadín, Oaxaca, Don Espadín",
  },
  media: [
    { ...initialState.media[0], sourceType: "remote", url: cmsAssets.hero, altText: "Don Espadín Mezcal Espadín hero product recognition image", approvalStatus: "SUPPLIER_EVIDENCE", usageRights: "CMS asset supplied by DOC ROI", isMain: true, order: 1 },
    { ...initialState.media[1], sourceType: "remote", url: cmsAssets.detail, altText: "Don Espadín Mezcal Espadín material quality detail image", approvalStatus: "SUPPLIER_EVIDENCE", usageRights: "CMS asset supplied by DOC ROI", isMain: false, order: 2 },
    { ...initialState.media[2], sourceType: "remote", url: cmsAssets.ritual, altText: "Don Espadín Mezcal Espadín ritual and use image", approvalStatus: "SUPPLIER_EVIDENCE", usageRights: "CMS asset supplied by DOC ROI", isMain: false, order: 3 },
    { ...initialState.media[3], sourceType: "remote", url: cmsAssets.packaging, altText: "Don Espadín Mezcal Espadín packaging and trust image", approvalStatus: "SUPPLIER_EVIDENCE", usageRights: "CMS asset supplied by DOC ROI", isMain: false, order: 4 },
  ],
  benefits: [
    { id: "benefit-origin", feature: "Oaxaca origin", benefit: "Builds provenance and category confidence for the buyer.", evidence: "PENDING" },
    { id: "benefit-agave", feature: "Agave Espadín", benefit: "Makes the product composition understandable for mezcal selection.", evidence: "PENDING" },
    { id: "benefit-format", feature: "750 ml · 43.6 ABV", benefit: "Clarifies format and technical comparison before purchase.", evidence: "Product data supplied" },
  ],
  trust: [
    { id: "claim-origin", claim: "Origin: Oaxaca, México", owner: "PENDING", source: "PENDING", status: "PENDING", reviewDate: "PENDING", approvalStatus: "PENDING", market: "PENDING" },
    { id: "claim-assets", claim: "Official product media supplied from DOC ROI CMS", owner: "DOC ROI", source: "CMS asset URLs", status: "SUPPLIER_EVIDENCE", reviewDate: "PENDING", approvalStatus: "SUPPLIER_EVIDENCE", market: "PENDING" },
  ],
  evidence: {
    trustBadges: "PENDING",
    originEvidence: "PENDING",
    lotEvidence: "PENDING",
    certificate: "PENDING",
    laboratoryEvidence: "PENDING",
    guarantee: "PENDING",
    supplierEvidence: "CMS assets supplied by DOC ROI",
    responsibleUse: "PENDING",
  },
  pricing: {
    ...initialState.pricing,
    currency: "EUR",
    grossPrice: 89,
    taxRate: 21,
    taxIncluded: true,
    referencePrice: 0,
    discountType: "NONE",
    discountValue: 0,
  },
  inventory: {
    stockStatus: "WAITLIST",
    stockQty: 0,
    lowStockThreshold: 5,
    availabilityMessage: "availability pending · join waitlist",
    nextLot: "PENDING",
    quantity: 1,
  },
  variants: [{ id: "variant-espadin", variant: "Espadín", option: "Foundational Edition", pack: "Bottle", quantity: "750 ml", personalisation: "PENDING" }],
  ctas: {
    primary: { enabled: true, label: "Buy now", action: "checkout", destination: "PENDING" },
    secondary: { enabled: true, label: "Ask for advice", action: "contact", destination: "PENDING" },
    personalisation: { enabled: false, label: "Personalize", action: "personalisation", destination: "PENDING" },
    save: true,
    share: true,
    help: true,
    chat: true,
  },
  commercialTerms: {
    paymentMethods: "PENDING",
    securePayment: true,
    shipping: "shipping pending",
    deliveryWindow: "delivery window pending",
    marketRestrictions: "PENDING",
    orderConditions: "PENDING",
    legalAge: "PENDING",
    returns: "returns policy pending",
    refund: "refund route pending",
    warranty: "protection pending",
  },
  service: {
    dispatchSla: "PENDING",
    deliverySla: "PENDING",
    carrier: "PENDING",
    breakagePolicy: "PENDING",
    incidentRoute: "PENDING",
    rma: "PENDING",
    returnsRoute: "PENDING",
    refundRoute: "PENDING",
    customerService: "customer service route pending",
    postSaleCommunication: "PENDING",
    stockIncidentHandling: "PENDING",
  },
  relationship: {
    customerArea: false,
    registration: "PENDING",
    consent: "PENDING",
    npsTrigger: "PENDING",
    referral: "PENDING",
    loyalty: "PENDING",
    reactivation: "PENDING",
    crmDestination: "PENDING",
  },
  seoAio: {
    seoTitle: "Don Espadín Mezcal Espadín · Foundational Edition",
    metaDescription: "Mezcal Espadín de Oaxaca en formato 750 ml y 43.6 ABV. PDP estructurada con precio, origen, media y evidencia pendiente visible.",
    keywords: "Don Espadín, Mezcal Espadín, Oaxaca, agave Espadín, mezcal ecommerce",
    semanticEntities: "Don Espadín; Mezcal Espadín; Oaxaca; México; Agave Espadín; Foundational Edition",
    faq: "PENDING",
    approvedClaims: "Only supplied product data and CMS asset provenance. Other claims remain PENDING.",
    productSchema: "PENDING",
    offerSchema: "PENDING",
    market: "PENDING",
    language: "Spanish",
    aiReadableConditions: "Unknown and pending fields must remain explicit. Do not invent certificates, reviews, stock, legal claims or availability.",
  },
  crossSell: [{ id: "cross-pending", type: "PENDING", title: "PENDING", price: "PENDING", cta: "PENDING" }],
  theme: {
    primaryColor: "#0B0F19",
    secondaryColor: "#C99A4A",
    backgroundColor: "#FFFFFF",
    ctaColor: "#05070B",
    fontOption: "Inter",
  },
  status: { publishStatus: "REVIEW" },
};